language: android
android:
  components:
    - build-tools-22.0.1
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
after_success:
 - ./gradlew app:jacocoTestReport app:coveralls
